# Generated by Django 3.0.8 on 2020-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albergue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('tipo', models.CharField(blank=True, default='', max_length=100)),
                ('comuna', models.CharField(blank=True, default='', max_length=100)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('direccion', models.CharField(blank=True, default='', max_length=100)),
                ('institucion', models.CharField(blank=True, default='', max_length=100)),
                ('horaio', models.CharField(blank=True, default='', max_length=100)),
                ('cupo', models.CharField(blank=True, default='', max_length=100)),
                ('mapa', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['region'],
            },
        ),
    ]
