# Generated by Django 3.0.8 on 2020-07-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigoAzul', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albergue',
            old_name='horaio',
            new_name='horario',
        ),
    ]
